# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/docker/repos/hdl/projects/mz7020_som_base_2023_2/mz7020_som_base.srcs/sources_1/bd/mz7020_som_base/ip/mz7020_som_base_proc_sys_reset_50MHz_0/mz7020_som_base_proc_sys_reset_50MHz_0.xci
# IP: The module: 'mz7020_som_base_proc_sys_reset_50MHz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/docker/repos/hdl/projects/mz7020_som_base_2023_2/mz7020_som_base.gen/sources_1/bd/mz7020_som_base/ip/mz7020_som_base_proc_sys_reset_50MHz_0/mz7020_som_base_proc_sys_reset_50MHz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mz7020_som_base_proc_sys_reset_50MHz_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/docker/repos/hdl/projects/mz7020_som_base_2023_2/mz7020_som_base.gen/sources_1/bd/mz7020_som_base/ip/mz7020_som_base_proc_sys_reset_50MHz_0/mz7020_som_base_proc_sys_reset_50MHz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mz7020_som_base_proc_sys_reset_50MHz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/docker/repos/hdl/projects/mz7020_som_base_2023_2/mz7020_som_base.gen/sources_1/bd/mz7020_som_base/ip/mz7020_som_base_proc_sys_reset_50MHz_0/mz7020_som_base_proc_sys_reset_50MHz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mz7020_som_base_proc_sys_reset_50MHz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/docker/repos/hdl/projects/mz7020_som_base_2023_2/mz7020_som_base.srcs/sources_1/bd/mz7020_som_base/ip/mz7020_som_base_proc_sys_reset_50MHz_0/mz7020_som_base_proc_sys_reset_50MHz_0.xci
# IP: The module: 'mz7020_som_base_proc_sys_reset_50MHz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/docker/repos/hdl/projects/mz7020_som_base_2023_2/mz7020_som_base.gen/sources_1/bd/mz7020_som_base/ip/mz7020_som_base_proc_sys_reset_50MHz_0/mz7020_som_base_proc_sys_reset_50MHz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mz7020_som_base_proc_sys_reset_50MHz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/docker/repos/hdl/projects/mz7020_som_base_2023_2/mz7020_som_base.gen/sources_1/bd/mz7020_som_base/ip/mz7020_som_base_proc_sys_reset_50MHz_0/mz7020_som_base_proc_sys_reset_50MHz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mz7020_som_base_proc_sys_reset_50MHz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/docker/repos/hdl/projects/mz7020_som_base_2023_2/mz7020_som_base.gen/sources_1/bd/mz7020_som_base/ip/mz7020_som_base_proc_sys_reset_50MHz_0/mz7020_som_base_proc_sys_reset_50MHz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mz7020_som_base_proc_sys_reset_50MHz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
